### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by mortezaalizadeh** [BuddyPlatform/parse-on-buddy-cli#14]
Hey guys, I am currently evaluating Buddy to see whether I can move my app to Buddy Parse cloud. I started trying to create static resources and upload it using the CLI command, but I got the following error. Environment variables are all set properly. Do you have any idea what wrong is with my machine?

I am using node v8.0.0.

morteza@MORTEZA ~/projects/micro-business/smart-grocery-backend-buddy $ parse-on-buddy -c 2
Listing application versions...
Walking local public directory subtree...
Listing existing hash blobs...
Uploading 1 (of 1) public asset(s)...
Uploading cloud code...
Uploading name → hash mapping...
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/compress-commons/lib/archivers/archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/zip-stream/index.js:157:49)
    at Zip.append (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/archiver/lib/plugins/zip.js:53:15)
    at Archiver._moduleAppend (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/archiver/lib/core.js:168:16)
    at Archiver._onQueueTask (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/archiver/lib/core.js:366:8)
    at /home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/async/dist/async.js:4069:9
    at process (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/async/dist/async.js:2317:17)
    at Immediate._onImmediate (/home/morteza/.nvm/versions/node/v8.0.0/lib/node_modules/parse-on-buddy/node_modules/async/dist/async.js:66:16)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by craigpatten** [comment]
Hi @mortezaalizadeh. This looks like archiverjs/node-archiver#236 and is fixed with Node ≥ v8.1.0.

**Comment by mortezaalizadeh** [comment]
Cheers man, upgraded to 8.1.4, it is all working now.
