### ISSUE TITLE
ECONNRESET - Failing to upload Cloud Code

### ISSUE THREAD

**Issue by mortezaalizadeh** [BuddyPlatform/parse-on-buddy-cli#16]
Started getting the following error since yesterday, can't upload my changes anymore. Here is my applicationID: 50a47f7f-411a-4abb-8c50-3daabac420eb

Any idea what is going on? Thank you.

Listing application versions...
Walking local public directory subtree...
Listing existing hash blobs...
1 public assets already synchronized!
Uploading cloud code...
Uploading name → hash mapping...
{ Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }

**Comment by craigpatten** [comment]
Hi @mortezaalizadeh. We're investigating.

**Comment by craigpatten** [comment]
We don't see any current problems with the CLI or the service but I'll follow up with you via our support system to verify that there aren't any issues specific to your Cloud Code directory. Thanks.

**Comment by mortezaalizadeh** [comment]
The issue was due to my Internet and network, so no problem related to the CLI. Cheers
